apiVersion: batch/v1
kind: Job
metadata:
  name: letsencrypt-certificates-job
  namespace: letsencrypt-job
spec:
  template:
    spec:
      containers:
        - image: quay.io/pittar/oc-acme:4.4
          env:
            - name: STAGING
              value: 'false'
          envFrom:
            - secretRef:
                name: cloud-dns-credentials
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash
              
              echo "Wait a few seconds for the secret to unseal."
              sleep 10              

              /scripts/aws.sh

              echo "Creating openid cert secret from OpenShift router cert."

              # Get name of certs secret.  It can be router-certs or router-certs-default.
              CERT_SECRET=$(oc get secrets -n openshift-ingress | grep router-certs | cut -d ' ' -f1)
              
              tlscert=`oc get secrets/$CERT_SECRET -o jsonpath={.data.'tls\.crt'} -n openshift-ingress | base64 --decode`
              oc create configmap openidcacrt --from-literal ca.crt="$tlscert" -n openshift-config

              echo "Done!"

          imagePullPolicy: Always
          name: letsencrypt-certificates-job
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: letsencrypt-job-sa
      serviceAccountName: letsencrypt-job-sa
      terminationGracePeriodSeconds: 30
