apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: container-security-operator
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: container-security-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: container-security-operator.v1.0.1
