# Copy your sealed-secrets-secert into this dir before running apply -k
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- sealed-secrets-namespace.yaml
- sealed-secrets-secret.yaml