kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
bases:
  - https://github.com/redhat-canada-gitops/catalog/rhsso/rhsso-instance/overlays/default

resources:
  - client-secret.yaml
  - openshift-realm.yaml
  - openshift-client.yaml

patchesJson6902:
  - target:
      group: keycloak.org
      version: v1alpha1
      kind: KeycloakClient
      name: openshift-client
    path: patch-redirect-uri.yaml
  - target:
      group: config.openshift.io
      version: v1
      kind: OAuth
      name: cluster
    path: patch-issuer.yaml