apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: groups-and-membership
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: cluster-nonprod/02-groups-roles-bindings
    repoURL: https://github.com/pittar-gitops/clusters.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
