apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: openshift-client
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: sso
spec:
  realmSelector:
    matchLabels:
      app: openshift
  client:
    clientId: openshift
    realm": "openshift"
    secret: 5e9326ee-ac8d-40bf-9060-e91dbe9d9000
    clientAuthenticatorType: client-secret
    consentRequired: false
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    redirectUris: 
        - "https://oauth-openshift.apps.czmyp3x3.canadacentral.aroapp.io/oauth2callback/rhsso"
     