kind: OAuth
apiVersion: config.openshift.io/v1
metadata:
  name: cluster
spec:
  identityProviders:
  - name: htpasswd
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-secret
  - name: rhsso
    mappingMethod: claim
    type: OpenID
    openID:
      clientID: openshift
      clientSecret: 
        name: openid-client-secret
      ca: 
        name: openidcacrt
      extraScopes: 
      - email
      - profile
      extraAuthorizeParameters: 
        include_granted_scopes: "true"
      claims:
        preferredUsername: 
        - preferred_username
        - email
        name: 
        - nickname
        - given_name
        - name
        email: 
        - custom_email_claim
        - email
      issuer: https://keycloak.example.com/auth/realms/openshift